# Generated by Django 5.0.4 on 2024-04-15 19:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False, verbose_name='id_ciudad')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False, verbose_name='id_perfil')),
                ('perfil', models.IntegerField(blank=True, null=True, verbose_name='perfil')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator], verbose_name='email'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fechanac',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='run'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to='web.ciudad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='web.perfil'),
        ),
    ]
