# Generated by Django 5.0.4 on 2024-04-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_ciudad_perfil_usuario_direccion_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='perfil',
            field=models.CharField(max_length=100, null=True, verbose_name='perfil'),
        ),
    ]
