# Generated by Django 5.0.4 on 2024-04-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_perfil_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.CharField(default='00000000-0', max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='run'),
        ),
    ]
