# Generated by Django 5.0.4 on 2024-04-15 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(default='2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='web.perfil'),
        ),
    ]
