# Generated by Django 5.0.4 on 2024-04-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre del producto'),
        ),
    ]
